### ISSUE TITLE
Problem sorting dates in Split Columns after Split Rows by term

### ISSUE THREAD

**Issue by cpiment** [fbaligand/kibana-enhanced-table#150]
Hi @fbaligand !

We are trying to draw a table using your plugin (plugin version 1.10, Kibana version 7.6.2) that shows us a metric for different tems (split rows, term aggregation) in different days (split cols, date histogram, interval daily)

![imagen](https://user-images.githubusercontent.com/10828255/96256168-723e0b80-0fb8-11eb-8220-a39ee3ebecbc.png)

The problem is that, since the A term has no data for date 2020/10/10, that column is shown at the end of the table, instead between 2020/10/9 and 2020/10/11. The same happens with 2020/10/11. We think that the problem may be that the table is filled line by line using the term data, and when term C appears with data for days 10 and 11, the columns are appended at the end. Is there any way to configure the plugin so the columns are ordered?

Thanks in advance for your help

**Comment by fbaligand** [comment]
Hi,

Split Columns are added, as things progress.
That is to say, columns are added as they come from Elasticsearch response.
If for the first term, there is no data for this date the column is not added. The column is added for the "C" term, so only on third line. 
That's why "2020-10-11" is the last column.

Now the good news: you can fix that with a simple configuration!

In your "Date Histogram" bucket, click on "Advanced", then set `{"min_doc_count": 0}` in JSON input.
And you're done!

**Comment by cpiment** [comment]
It works like a charm!

Thanks for your help and for taking time to test this :)

**Comment by cpiment** [comment]
Hi @fbaligand 

We have been testing more thoroughly, and we have detected that when the first date has value "0" for the aggregation for the term A, it also sends it to the end of the table when term C has value for the first date. The "min_doc_count" trick doesn´t seem to work for this case.

I have been reading the documentation of the histogram aggregation to see if other option could adjust this behaviour and I can't find anything useful, do you have any ideas about this?

**Comment by fbaligand** [comment]
I just tried the same use case, with a "Split Rows" bucket using Terms aggregation, then a "Split Cols" bucket using date_histogram aggregation, then a "Sum" metric.
I used "kibana_sample_data_flights" sample data and deleted some data to reproduce your exact case.

But I don't reproduce your issue.
Using `{"min_doc_count": 0}`, the buckets are sorted in the right order, even if first row, second column displays 0.

![image](https://user-images.githubusercontent.com/3750300/96641407-f54ac300-1324-11eb-810e-ea6330ef987b.png)

**Comment by cpiment** [comment]
Sorry for the delay I'm taking to update you this issue. I'm working on a way to reproduce the issue and I will get you back with my findings.

**Comment by DDSGooch** [comment]
I have a very similar problem. Has any progress been made on this? Many thanks

**Comment by fbaligand** [comment]
So that I can reproduce your issue, could you export your data?
Ideally, with "bulk" format, or with CSV format.
Thus, could you indicate your Kibana version?

**Comment by DDSGooch** [comment]
I'm not sure if this is what you mean but I've here's the CSV file for that data, obtained by doing an Inspect on the data from Kibana. Let me know if this isn't what you meant. By the way, I had to rename the file to a text file, otherwise github wouldn't upload it. Again if that's not correct let me know.
[EnhancedTableDateOrder.txt](https://github.com/fbaligand/kibana-enhanced-table/files/6334409/EnhancedTableDateOrder.txt)

I'm using Kibana version 7.10.1

Many thanks

**Comment by fbaligand** [comment]
I just tested your dataset.
And I reproduce your issue.

The problem comes from that for the first row (category A), you don't have data for the very first day.
And so, given the way "date histogram" works, for A bucket, it does not start the date histogram at "2021-03-30".
If you change order to "Alphabetical" in your "Split Rows" bucket, you will see that it works.

That said, I will try to find a way to fix the problem in the plugin.
It will ask to add some ascending sorting in the split columns.

**Comment by DDSGooch** [comment]
Many thanks for looking at that and I'm glad you've managed to reproduce it and I look forward to an update to the plugin.
Unfortunately changing the sorting order on the "Split Rows" bucket won't fix it for me, as the data I sent to you was just some sample data that I used as a simple example. My real data is much more complicated and sorting the rows in alphabetical order won't guarantee that the first row won't have a missing date in the same way as my simple example does.

Let me know if I can be of any help.

**Comment by cpiment** [comment]
Thanks for keeping this open. I'm sorry I had not been able to obtain a dataset for you to reproduce the issue. Thanks @DDSGooch for that.

We have the same problem: Sorting the rows alphabetically doesn't fix the problem either.

**Comment by fbaligand** [comment]
Great news: Enhanced Table v1.13.0 is out with this issue fixed by a new option "Sort split cols"!
Numerous other enhancements are also available.

Check it there:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.0
