### ISSUE TITLE
Unable to install enhanced - table in kibana 7.10.1

### ISSUE THREAD

**Issue by ddelliosRJ** [fbaligand/kibana-enhanced-table#160]
Hi! 

I am on kibana 7.10.1 and following error occurs when trying to install enhanced table 1.10.1:
`Plugin installation was unsuccessful due to error "Plugin enhancedTable [kibana] is incompatible with Kibana [7.10.1]"`

I am running this command: 
`sudo -u kibana bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.10.1/enhanced-table-1.10.1_7.10.1.zip`

I have also tried as root with the --allow-root option or locally with the file:/// option but results are the same...

Can you help me?

**Comment by fbaligand** [comment]
Hi,
Thanks for the issue.
The problem is because kibana specific version is missing in `kibana.json` file (inside plugin package).
I just fixed the problem (and tested it).
And I republished enhanced-table-1.10.1_7.10.0.zip and enhanced-table-1.10.1_7.10.1.zip on GitHub.
So please, download again package here and retry plugin installation:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.10.1/enhanced-table-1.10.1_7.10.1.zip

**Comment by ddelliosRJ** [comment]
Everything is working as it should. Thanks and kudos for the good work!

**Comment by fbaligand** [comment]
Nice!
Thanks for the feedback!
