### ISSUE TITLE
Average not showing proper in Grid

### ISSUE THREAD

**Issue by Sagesh** [fbaligand/kibana-enhanced-table#208]
I created a widget with the count, Average Time, and Max Time. I can see count and Max Time is coming correct in the table but the average is not showing correctly.

Example
![image](https://user-images.githubusercontent.com/23548722/117666866-ed1f7b80-b1c1-11eb-9726-4c3274a10f17.png)

Thanks for all the help and support

**Comment by fbaligand** [comment]
Well, I don’t see something incorrect in your screenshot.
What is incorrect up to you?

**Comment by Sagesh** [comment]
Hi Fabien,

Thanks for your quick response.

As per my understanding, the Average should be TotalTime / No of records
Here total time is  623 and No of records is 1 so I am expecting the Average also 623 (623/1) instead of 311.5

I think the table is showing  Average as 623/2

**Comment by fbaligand** [comment]
Well, several remarks:
- your third column is not total time, but max time, that's quite different, because total time is the "sum" of all times.
- as you say, given that Count=1, average time should equal to max time
- metrics are computed by Kibana core, not enhanced table plugin
- I just tried a similar case than yours (Count=1, Average Metric, Max Metric), and I don't reproduce your issue.
- could you test exactly the same buckets/metrics with classic Data Table to see if you reproduce the same issue?
- could you screenshot here all your vis settings: 'Data' and 'Options' tabs?
