### ISSUE TITLE
Installing the plugin in Redhat

### ISSUE THREAD

**Issue by sajeew-ganesh** [fbaligand/kibana-enhanced-table#215]
I was checking on the methods to install the plugin in a linux machine. Is there a place where i can refer it?

**Comment by sajeew-ganesh** [comment]
I am using Kibana 7.8.0 i downloaded the version Enhanced-Table-1.9.2

`sudo -u kibana ./bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.9.2/enhanced-table-1.9.2_7.8.0.zip`

This gives the following error

sudo: unknown user: kibana
sudo: unable to initialize policy plugin

**Comment by fbaligand** [comment]
Hi,

First, given your error, it seems that "kibana" user does not exist on your machine.

Then, you have to know that Kibana 7.8.0 is not supported by the plugin, because there is a blocking issue in Kibana 7.8.0 that has been fixed in Kibana 7.8.1.

So, once you fixed your "kibana" user problem, I invite you to use Kibana 7.8.1 and so, download enhanced table for Kibana 7.8.1:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.9.2/enhanced-table-1.9.2_7.8.1.zip

By the way, you can also download latest plugin version (1.11.0) for kibana 7.8.1:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.11.0/enhanced-table-1.11.0_7.8.1.zip

**Comment by fbaligand** [comment]
Given that question is answered, I close the issue.
