### ISSUE TITLE
Enhanced Table plugin for Kibana 7.16 and 7.17

### ISSUE THREAD

**Issue by suchi1686** [fbaligand/kibana-enhanced-table#237]
Hello Team, currently Enhance table plugin is supported upto 7.15.2. Due to log4j issue, we had to upgrade the elastic to 7.16.2. Please let me know when can we expect the update to the new version.

**Comment by fbaligand** [comment]
Hi,

I fully understand your situation.
That said, after a first analysis, kibana 7.16 removed an important component required by enhanced table plugin (angularjs integration component).
So, at this point, I don’t know yet how I will be able to migrate the plugin.
And  I know even less when.

That said, due to elasticsearch security manager, elasticsearch 7.0+ with jdk 9+ is not vulnerable.
As explained here:
https://discuss.elastic.co/t/apache-log4j2-remote-code-execution-rce-vulnerability-cve-2021-44228-esa-2021-31/291476

**Comment by talcoh2x** [comment]
@fbaligand  there is a plan to support 7.16+?

**Comment by fbaligand** [comment]
Yes, it is a aim. 
But as said in my previous comment, it will not be easy.

**Comment by bhavinshah1086** [comment]
Hi, I appreciate efforts you and your team have put to make this plugin. This plugin has really provided us great insights in terms of seeing data in better way. 

My challenge is I am on 7.10 and using this plugin. Our infra guy is asking to update entire stack with latest version due to Log4j issue. It would be great if we can atleast know by when you are planning to release it so we can also plan accordingly.

I am very much thankful for this plugin.


Regards

**Comment by fbaligand** [comment]
Well, there are other solutions. 
in my company, we patch log4j jar directly by removing JndiLookup class.
If you use es 7.x with jdk9+, your es is not vulnerable.

More details on vulnerabilities and solutions here:
https://discuss.elastic.co/t/apache-log4j2-remote-code-execution-rce-vulnerability-cve-2021-44228-esa-2021-31/291476

**Comment by massimobrignoli** [comment]
The patch is not a solution. The 7.17 is already out and the 8.0 will be released in few weeks. I'm an Elastic employee and I have to congratulate for your work! I know many elastic users using enhanced table so I think you need to find a definitive solution. Let me know if you need any help.

**Comment by fbaligand** [comment]
Hi @massimobrignoli, 
Thanks for your answer.

You say that patch is not a solution.
Well, that is officially a solution given by Elastic Security Team here for some Elasticsearch versions:
https://discuss.elastic.co/t/apache-log4j2-remote-code-execution-rce-vulnerability-cve-2021-44228-esa-2021-31/291476#elasticsearch-mitigation-summary-matrix-37

Then, to be precise, Kibana 7.17 is still not yet out, even the "v7.17.0" tag has not been created:
https://github.com/elastic/kibana/releases

Well, I would love to quickly provide enhanced-table plugin for Kibana 7.16.
But it's pretty hard because each Kibana core minor version brings breaking changes, not documented, and sometimes very hard.

For Kibana 7.16, all AngularJS integration code has been removed from Kibana repository, that is really critical for enhanced-table plugin.
This is the reason why enhanced-table for Kibana 7.16 is still not out.

**Comment by jmliu1983** [comment]
Star for you, thanks a lot for this great plugin

**Comment by fbaligand** [comment]
Great news: Enhanced Table v1.13.0 is out with Kibana 7.16 and 7.17 support!
Numerous other bug fixes and one enhancement are also available.

Check it there:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.0

**Comment by fbaligand** [comment]
Hi,

For information, package for Kibana 7.17.1 is now available here:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.0_7.17.1.zip

**Comment by fbaligand** [comment]
Enhanced Table plugin version 1.13.2 is out, with support for all these Kibana versions: 7.16, 7.17, 8.0, 8.1 and 8.2!

You can get the packages here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.2
