### ISSUE TITLE
Enhance table plugin is available for 7.16.3

### ISSUE THREAD

**Issue by AH-Siva** [fbaligand/kibana-enhanced-table#248]
Hello @cpiment @fbaligand, 
Good noon!

Could see currently Enhance table plugin is available and support able upto 7.15.2 version. we are in the plan of ELK stack upgrade from 7.11.2 to 7.16.3 latest version. 

In my company, we have built lots of visualizations with enhanced table. If Enhance table is not available and not supported to the latest version, then it's very big road block of our upgrade. 

Kindly let me know when can we expect the update to the new version (7.16.3)? Will enhance table 7.15.2 supports and work for the new version?

Thanks | Siva

**Comment by fbaligand** [comment]
Well, sorry, but enhanced-table for Kibana 7.15.2 doesn't work for Kibana 7.16.
Unfortunately, this is not easy to migrate enhanced-table for Kibana 7.16, given that Kibana 7.16 has a very breaking change really not easy to deal with.

Finally, I close this issue, in favor of this one because it's a duplicate: #237

**Comment by AH-Siva** [comment]
@fbaligand  - Thanks for the response! 

Is there any tentative plan for new release? 

It would be more helpful if we could get a some ETA on this? So, that we will plan our upgrade accordingly. 

Thanks 
Siva
