### ISSUE TITLE
Failed to instantiate module / Angular issue ?

### ISSUE THREAD

**Issue by adm-crow** [fbaligand/kibana-enhanced-table#254]
Hello,

I have installed the enhanced table plugin (v7.16.2) on my redhat server.
Everything's good but when I want to create an Enhanced Table Visualization, I got this error :

_[$injector:modulerr] Failed to instantiate module kibana/enhanced_table_vis due to:
[$injector:modulerr] Failed to instantiate module tableVisI18n due to:
[$injector:pget] Provider 'i18n' must define $get factory method._

The Angular documentation say this :
_This error occurs when attempting to register a provider that does not have a $get method_
https://code.angularjs.org/1.8.2/docs/error/$injector/pget

I don't have skills to fix this issue... Anyone can help me ?

Thank's

**Comment by adm-crow** [comment]
My bad ! I found this thread that already speaking about this issue : https://github.com/fbaligand/kibana-enhanced-table/discussions/253
I close this issue.

**Comment by fbaligand** [comment]
Hi @adm-crow,

Actually, this error is very weird because:
- `$get` function is defined in 'i18n' provider: https://github.com/fbaligand/kibana-enhanced-table/blob/master/public/angular/i18n/provider.ts#L25
- With exactly the same enhanced-table code, it doesn't work for Kibana 7.16.0 to Kibana 7.16.2, but it works for Kibana 7.16.3+ and also Kibana 7.15.x

That's why the recommendation is to use Kibana 7.16.3.
And given, that enhanced-table is totally not usable with this bug, I will remove packages for Kibana 7.16.0 to 7.16.2.

**Comment by adm-crow** [comment]
Thanks for your answer @fbaligand !
I have updated to the 7.17 version and all is fine ! :)
