### ISSUE TITLE
Enhancement: Reference columns by label instead of number

### ISSUE THREAD

**Issue by rettops** [fbaligand/kibana-enhanced-table#27]
Would it be possible to reference columns by label instead of number?  Whenever I add / subtract / move columns, I have to fix all of the computed columns to match the new numbering.

**Comment by fbaligand** [comment]
Hi @rettops,

I understand your issue when you add/remove buckets/metrics and have to renum columns references. 

That said, you can have the same issue with labels, when you change labels.

Thus, it’s not easy to implement, because at low level, formula references simple variables. So I would have to translate labels (col[‘Label’]) to variables (col0).

Finally, columns do not always have a label (they have default label computed by Kibana)

But if you want to make a PR that implements the feature, don’t hesitate!
I will be happy to merge it!

**Comment by fbaligand** [comment]
Hi @rettops 

I have great news for you: I just released enhanced-table v1.1.0, with the feature you wish here!
So now, in a computed column formula, you can reference another column by its label!
For example: `col['Sum of duration'] / col['Count']`

There are also some other new features!
Check it out here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.1.0

**Comment by rettops** [comment]
Great, thanks!!!!

**Comment by fbaligand** [comment]
Happy to see you enjoy the feature :)
