### ISSUE TITLE
Issue in installing plugin, name not listed under plugins when starting kibana

### ISSUE THREAD

**Issue by dobydx** [fbaligand/kibana-enhanced-table#348]
Hi,

I've upgraded my Kibana to 8.9.2, older enhanced-table is broken.
So I'm trying to install the correct version, but failing to do so.

Steps I'm following:

> 1. systemctl stop kibana
> 2. rm -rf optimize folder
> 3. from kibana home folder: ./bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.4/enhanced-table-1.13.4_8.9.2.zip
> 4. Installs successfully
> 5. systemctl start kibana -> enhancedTable is not listed in plugins list
> 6. Cache for forever is deleted
> 7. Hard refresh for the Kibana UI
> 8. Error as seen in screenshot
![enhancedTable_install_fails](https://github.com/fbaligand/kibana-enhanced-table/assets/8556430/1b27ce5a-b8ca-431d-af2b-fdbcdd0bce97)

Any help is much appreciated.

**Comment by fbaligand** [comment]
Hi,

Well, I just tried to install plugin v1.14.0 on Kibana 8.9.0 (I had this Kibana version on my computer). And it works fine.
Some advices:
- first, don't delete "optimize" folder. Since Kibana 7.9, it is not necessary and especially not useful. Maybe it can cause some errors.
- then use the very last plugin version (v1.14.0). So I invite you to install this package:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.14.0/enhanced-table-1.14.0_8.9.2.zip
