### ISSUE TITLE
Configure a watcher based on the table value

### ISSUE THREAD

**Issue by krishnacm** [fbaligand/kibana-enhanced-table#43]
I want to make a pivot table with the rows from a field value and columns are the weekdays. Also I have a reference table having max values for each row-columns of the table. Is it possible by using this pivot table. Also most importantly, I need to sent emails (from watcher), if the threshold of the pivot table is reached on comparing with the reference table values.

**Comment by fbaligand** [comment]
If you want to do a watcher based on tabular values, enhanced-table plugin can't do anything for you. Sorry.
Because, watcher/email alerting is based on elasticsearch queries, not on Kibana visualization results.

Probably the best way to do that, is to create a watcher that executes a SQL query on elasticsearch. It allows to easily get tabular results, compared to a classic aggregations query.

**Comment by krishnacm** [comment]
Thanks for the update, will check with some scripts.
