### ISSUE TITLE
Using string functions

### ISSUE THREAD

**Issue by joe-w** [fbaligand/kibana-enhanced-table#75]
Can someone provide an example for how to use string functions in either the Computed Column -> Formula field, or in the Computed Column -> Template.
As a simple example, I'm trying to split a string on '-', and would like to use:
substring(col['name'], indexOf(col['name'], '-')+1)
String functions in "Formula" always give me errors.
String functions with more than one argument don't seem to work in the Template.
{{encodeURIComponent col['name']}} - works
{{substring col['name'] 5}} does not seem to work

**Comment by fbaligand** [comment]
Hi,

I just tried exactly your first Formula (`substring(col['name'], indexOf(col['name'], '-')+1)`) and it works fine.
So I have just some questions:
- Is "Format" combobox is set to String?
- Does the referenced column has "name" in "Label" field?
- Which plugin and Kibana version do you use?

Concerning template, only encodeURIComponent function is available. Other string functions are not available. Templates are there to render the column value, not to compute the value. "encodeURIComponent" function is available in template because you may need the value as is for display, and the value url-encoded for an URL, and both in same template.
For example:
`<a href="my-dashboard?param={{{encodeURIComponent value}}}">{{value}}</a>`

**Comment by joe-w** [comment]
Thanks. I understand the distinction between formula and template, but was
trying to build a URL from multiple fields. I can do the same by using
multiple formulae and hiding the intermediate columns, so that's cool.
Thanks for a VERY valuable plugin!

--> joe w.

**Comment by fbaligand** [comment]
Nice way to achieve your goal 😁
And happy to see that you appreciate the plugin 😁
