### ISSUE TITLE
Computed column - Multiple expressions do not work

### ISSUE THREAD

**Issue by XavierRamosORGADATA** [fbaligand/kibana-enhanced-table#91]
Kibana 7.5.1
Enchanced table - 1.7.0

Hi, your plugin is great! In the last release you've included a new feature: 
-Evaluate multiple expressions by separating them with ";".

However, I've tried to run multiple expressions through the "Lines computed filter" and it seems as it only uses the last one on the right and disregards the others.

![image](https://user-images.githubusercontent.com/60776623/74836026-d66fd900-531e-11ea-8d63-d7112cde15c2.png)

![image](https://user-images.githubusercontent.com/60776623/74836066-eedff380-531e-11ea-81d5-a851493ca622.png)

![image](https://user-images.githubusercontent.com/60776623/74836329-77f72a80-531f-11ea-95e6-2bd2e08acaa1.png)

![image](https://user-images.githubusercontent.com/60776623/74836368-8b09fa80-531f-11ea-96c1-6061297a263a.png)

**Comment by fbaligand** [comment]
Hi,

Well, this is expected behavior of multiple expressions.
You can chain several expressions (with variables, ...), and last expression is returned as result.
So it is like : `x = col0; return x`

if you want to do a "Lines computed filter" with multiple conditions, you should use one expression and use `and and `or` operators.
For example: `col0 > 30 and col1 > 300`

You can see more documentation on that here:
https://github.com/silentmatt/expr-eval#expression-syntax

**Comment by 3DWhiz** [comment]
Great! Thank you!!
