### ISSUE TITLE
enhanced-table-1.8.0_7.6.0 installation Error

### ISSUE THREAD

**Issue by Ravindrasch** [fbaligand/kibana-enhanced-table#92]
Hi,
i am unable to install the enhanced-table-1.8.0_7.6.0 plugin.
![test](https://user-images.githubusercontent.com/61861641/76057072-4aa4b080-5f9e-11ea-8bcf-8ca0bfcdbc7b.PNG)
kindly help on this issue.

**Comment by fbaligand** [comment]
Hi,

After some discussion with Kibana core team, it seems to be a Kibana core bug.
So I just created an issue on Kibana repository:
https://github.com/elastic/kibana/issues/59543

That said, waiting that issue is fixed, you can do like this:
- unzip manually enhanced-table-1.8.0_7.6.0.zip into `%KIBANA_HOME%\plugins`
- move `%KIBANA_HOME%\plugins\kibana\enhanced-table` to `%KIBANA_HOME%\plugins\enhanced-table`
- remove `%KIBANA_HOME%\plugins\kibana` 
- remove `%KIBANA_HOME%\optimize` 
- start `%KIBANA_HOME%\bin\kibana.bat`

**Comment by fbaligand** [comment]
Hi, 

Issue has been fixed by kibana core team here:
https://github.com/elastic/kibana/pull/59570

It will be released in kibana 7.6.2

Waiting this release, you can use one of my two tips. 

As issue is answered, I close the issue.

**Comment by fbaligand** [comment]
I realized that I didn’t publish the other (cleaner) way to install the plugin:
- cd %KIBANA_HOME%
- bin\kibana-plugin.bat https://...

The important thing is the precise folder where you are, when you launch kibana-install command.

**Comment by fbaligand** [comment]
I just updated README install guide, to give a procedure compatible with Kibana 7.6:
https://github.com/fbaligand/kibana-enhanced-table#install
