### ISSUE TITLE
Table does not immediately display

### ISSUE THREAD

**Issue by mxfwang** [fbaligand/kibana-enhanced-table#99]
Hello,

First of all, thank you so much for your work! It really fills a much needed void of kibana.

I'm having a problem where when I open the visualization or refresh the data, the table could take a really long time to display, or not at all. However, if I click another something, say if I was in the Data tab and I click Options, then the table displays immediately. This happens both in the visualization and in a dashboard.

I'm guessing this has something to day with the size of my table? Usually the time range I want to look at has ~100 rows. When I filter down to a small range, where there are only 10-20 rows, the table shows up faster. However, it's still strange that it displays immediately even with 100 rows after I click around.

I have a separate question that I don't think warrant its own issue, so I'll tag it here. (Please let me know if I need to split it out. I have a computed column (call that C) that is the ratio of two other columns (call them A and B). I also want to display the total of all columns. Ideally, I'd like the total of C to be total(A) / total(B). But it looks like kibana does the total after the column is computed, so the total of C is the sum of percentages, which does not make sense. I'm wondering if you have a workaround for this?

Thank you in advance for your help!

**Comment by fbaligand** [comment]
Hi,

These are very different issues :)

For the first one, I'm surprised, because I have tests with 500 rows, that display fast (less than 1s).
Thus, in last version (1.8.0), I fixed some similar blank screen problems for Kibana 7.2+.
If you don't use last plugin v, ersion, I invite you to install the latest.
Then, can you tell me which Kibana version you use?
Finally, do you have some errors in your browser console (in Development Tools)?

Concerning your second issue, I confirm that, by default, total is the sum of C column values (so sum of the ratios A / B).
The closest way to get what you want is to choose "Average" in "Total function" option.

**Comment by mxfwang** [comment]
The problem went away after updating to the newest version (and docker prune in between, not sure if that helped). Thank you!

**Comment by fbaligand** [comment]
Great!
Thanks for feedback!

**Comment by fbaligand** [comment]
@mxfwang 
Concerning your second issue, this feature request (#100) should answer your need.
I don't promise that I will implement it, but I plan to.
